AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/ClassVars:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
  - './lib/**/cli.rb'
  - './lib/**/repository.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
  - '*.gemspec'
  - './lib/**/cli.rb'
  - './lib/**/repository.rb'
  - './spec/**/*'

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
  - './lib/**/upgraderepo.rb'
  - './lib/**/repository.rb'
  - './lib/**/view.rb'
  - './lib/**/traversable.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
  - './lib/**/upgraderepo.rb'
  - './lib/**/repository.rb'
  - './lib/**/view.rb'
  - './lib/**/traversable.rb'

Lint/UriEscapeUnescape:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
  - './lib/**/local.rb'

Style/MixinUsage:
  Enabled: true
  Exclude:
  - './spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
  - './bin/*'
  - './exe/*'
