# plugins:
  # - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - './lib/**/view.rb'
    - './lib/**/cli.rb'
    - './lib/**/traversable.rb'

Metrics/AbcSize:
  Exclude:
    - './lib/**/view.rb'
    - './lib/**/traversable.rb'
    - './lib/**/cli.rb'

Metrics/ClassLength:
  Exclude:
    - './lib/**/cli.rb'
    - './lib/**/upgraderepo.rb'

Metrics/BlockLength:
  Exclude:
    - './lib/**/cli.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - './lib/**/view.rb'
    - './lib/**/traversable.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - './lib/**/view.rb'
    - './lib/**/traversable.rb'
